{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryptomator-hub.fullname" . }}-secrets-minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cryptomator-hub.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
stringData:
  minio_root_user: {{ .Values.minio.auth.rootUser | quote }}
  minio_root_password: {{ include "katta-server.resolvedMinioRootPassword" . | quote }}
{{- end }}
