{{- if .Values.hub.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "katta-server.fullname" . }}-secrets-hub
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "katta-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  hub_system_client_secret: {{ include "katta-server.resolvedSystemClientSecret" . | quote }}
  hub_admin_password: {{ include "katta-server.resolvedHubAdminPassword" . | quote }}
  hub_db_password: {{ include "katta-server.resolvedHubDbPassword" . | quote }}
  hub_initial_id: {{ .Values.hub.secrets.initialId | quote }}
  hub_initial_license: {{ .Values.hub.secrets.initialLicense | quote }}
{{- end }}
