{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "katta-server.fullname" . }}-secrets-pg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "katta-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  pg_admin_password: {{ include "katta-server.resolvedPostgresAdminPassword" . | quote }}
  initdb.sql: |-
    {{- if .Values.keycloak.enabled }}
    CREATE USER {{ .Values.keycloak.database.username }} WITH ENCRYPTED PASSWORD '{{ include "katta-server.resolvedKeycloakDbPassword" . | replace "'" "''" }}';
    CREATE DATABASE {{ .Values.keycloak.database.name }} WITH ENCODING 'UTF8' OWNER {{ .Values.keycloak.database.username }};
    {{- end }}
    CREATE USER {{ .Values.hub.database.username }} WITH ENCRYPTED PASSWORD '{{ include "katta-server.resolvedHubDbPassword" . | replace "'" "''" }}';
    CREATE DATABASE {{ .Values.hub.database.name }} WITH ENCODING 'UTF8' OWNER {{ .Values.hub.database.username }};
{{- end }}
