package org.cryptomator.hub.api.cipherduck;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Part of vault JWE specifying the vault metadata.
 * Allows to create a bookmark in the client referencing the vendor in the storage profiles.
 * This Java record is unused in hub, only its ts counterpart in `storage.ts`.
 * Cipherduck client uses code generated by the OpenAPI generator.
 */
public record VaultMetadataJWEStorageDto(
		@JsonProperty(value = "provider", required = true)
		// references id in StorageProfileDto (aka. vendor in client profile)
		String provider,
		@JsonProperty(value = "defaultPath", required = true)
		String defaultPath,
		@JsonProperty(value = "nickname", required = true)
		String nickname,
		@JsonProperty(value = "region", required = true)
		String region,

		@JsonProperty(value = "username")
		// for non-STS
		String username,
		@JsonProperty(value = "password")
		// for non-STS
		String password
) {
}