name: CI Build

on:
  push:
  pull_request_target:
    types: [labeled]

env:
  NODE_VERSION: 22
  JAVA_VERSION: 21

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      # / katta start addition
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Generate openapi.json
        working-directory: backend
        run: >
          mvn -B clean compile quarkus:build -P generate-openapi-json
      - name: Check openapi.json
        working-directory: backend
        run: >
          cat ../frontend/src/openapi/openapi.json
      # \ katta end addition
      - name: NPM install
        working-directory: frontend
        run: npm ci --ignore-scripts
      - name: Build and test frontend
        working-directory: frontend
        run: npm run test:coverage
      - name: Deploy frontend
        working-directory: frontend
        run: npm run dist
      # / katta start commented out
      #      - name: SonarCloud Scan Frontend
      #        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
      #        with:
      #          projectBaseDir: frontend
      #          args: >
      #            -Dsonar.organization=cryptomator
      #            -Dsonar.projectKey=cryptomator_hub_frontend
      #            -Dsonar.typescript.tsconfigPath=tsconfig.json
      #            -Dsonar.sources=src/
      #            -Dsonar.tests=test/
      #            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      #          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # \ katta start commented out
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      # / katta start commented out
      #      - name: Cache SonarCloud packages
      #        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      #        with:
      #          path: ~/.sonar/cache
      #          key: ${{ runner.os }}-sonar
      #          restore-keys: ${{ runner.os }}-sonar
      # \ katta start commented out
      - name: Build and test backend
        working-directory: backend
        run: >
          ./mvnw -B clean verify
          # / katta start commented out
          #          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          #          -Dsonar.projectKey=cryptomator_hub_backend
          #          -Dsonar.organization=cryptomator
          #          -Dsonar.host.url=https://sonarcloud.io
          # \ katta start commented out
          --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      # / katta addition
      - id: get_tag
        name: Get tag
        working-directory: backend
        run: |
          if [[ ! -z "${{ inputs.tag }}" ]]; then
            TAG="${{ inputs.tag }}"
          elif [[ ${{ github.ref_type }} == 'tag' ]]; then
            TAG="${{ github.ref_name }}"
          # / katta start modification
          elif [[ ${{ github.ref_name  }} == ${{ github.event.repository.default_branch }} ]]; then
            TAG=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          else
            TAG="commit-${{ github.sha }}"
          fi
          # \ katta end modification
          echo tag=${TAG}
          echo tag=${TAG} >> "$GITHUB_OUTPUT"
      - name: Build and push container image (ci)
        working-directory: backend
        run: ./mvnw -B clean package -DskipTests
        env:
          QUARKUS_JIB_PLATFORMS: linux/amd64,linux/arm64/v8
          QUARKUS_CONTAINER_IMAGE_TAG: ${{ steps.get_tag.outputs.tag }}-ci
          QUARKUS_CONTAINER_IMAGE_BUILD: true
          QUARKUS_CONTAINER_IMAGE_PUSH: true
          QUARKUS_CONTAINER_IMAGE_REGISTRY: ghcr.io
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ github.actor }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      # \ katta addition

  build-native-image:
    name: Build and Push ${{ matrix.arch }} Image
    needs: test
    # / katta start commented out - build every commit
    # if: startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[build image]')
    # \ katta end commented out
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
            arch: amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
            arch: arm64
    runs-on: ${{ matrix.os }}
    outputs:
      digest_amd64: ${{ steps.digest.outputs.digest_amd64 }}
      digest_arm64: ${{ steps.digest.outputs.digest_arm64 }}
    permissions:
      contents: read # Required for checkout
      packages: write # Required for pushing the image to GHCR
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      # / katta addition
      - id: get_tag
        name: get tag
        working-directory: backend
        run: |
          if [[ ! -z "${{ inputs.tag }}" ]]; then
            TAG="${{ inputs.tag }}"
          elif [[ ${{ github.ref_type }} == 'tag' ]]; then
            TAG="${{ github.ref_name }}"
          # / katta start modification
          elif [[ ${{ github.ref_name  }} == ${{ github.event.repository.default_branch }} ]]; then
            TAG=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          else
            TAG="commit-${{ github.sha }}"
          fi
          # \ katta end modification
          echo tag=${TAG}
          echo tag=${TAG} >> "$GITHUB_OUTPUT"
        # \ katta addition
      - name: NPM install
        working-directory: frontend
        run: npm ci --ignore-scripts
      - name: Deploy frontend
        working-directory: frontend
        run: npm run dist
      - name: Ensure to use tagged version
        working-directory: backend
        # / katta modification
        #run: ./mvnw versions:set --file pom.xml -DnewVersion=${GITHUB_REF##*/}
        run: ./mvnw versions:set --file pom.xml -DnewVersion=${{ steps.get_tag.outputs.tag }}
        # \ katta modification
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ghcr.io/shift7-ch/katta-server
          # / katta modification
          tags: |
            type=sha,prefix=,format=short
            type=raw,value=${{ steps.get_tag.outputs.tag }}
            type=raw,value=latest,enable={{is_default_branch}}
          # \ katta modification
          flavor: |
            suffix=-${{ matrix.arch }}
          labels: |
            org.opencontainers.image.title=Katta Server
            org.opencontainers.image.vendor=Shift 7 GmbH
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Login to GHCR
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Container Image
        id: push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: backend
          file: backend/src/main/docker/Dockerfile.native
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
      - name: Export Digest
        id: digest
        run: |
          echo "digest_${{ matrix.arch }}=${{ steps.push.outputs.digest }}" >> "$GITHUB_OUTPUT"



  multi-arch-image:
    name: Build and Push Multi-Arch Image
    needs: build-native-image
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for checkout
      id-token: write # Required for the attestations step
      attestations: write # Required for the attestations step
      artifact-metadata: write # Required for the attestations step
      packages: write # Required for pushing the image to GHCR
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Determine short Commit SHA
        id: sha
        run: echo "short_sha=${LONG_SHA:0:7}" >> "$GITHUB_OUTPUT"
        env:
          LONG_SHA: ${{ github.sha }}
      - name: Login to GHCR
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Multi-Arch Manifest for ghcr.io/shift7-ch/katta-server:${{ steps.sha.outputs.short_sha }}
        run: >
          docker buildx imagetools create --tag ghcr.io/shift7-ch/katta-server:${{ steps.sha.outputs.short_sha }}
          ghcr.io/shift7-ch/katta-server@${{ needs.build-native-image.outputs.digest_amd64 }}
          ghcr.io/shift7-ch/katta-server@${{ needs.build-native-image.outputs.digest_arm64 }}
      - name: Retrieve Multi-Arch Digest
        id: inspect
        run: |
          DIGEST=$(docker buildx imagetools inspect ghcr.io/shift7-ch/katta-server:${{ steps.sha.outputs.short_sha }} --format "{{json .Manifest}}" | jq -r .digest)
          echo "digest_multiarch=${DIGEST}" >> "$GITHUB_OUTPUT"
      - name: Generate artifact attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: ghcr.io/shift7-ch/katta-server
          subject-digest: ${{ steps.inspect.outputs.digest_multiarch }}
          push-to-registry: true

# / katta start addition
  keycloak-integrationtests:
    name: Run katta Keycloak Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
      - name: Run Keycloak integration tests
        working-directory: keycloak
        run: >
          mvn -B clean verify
# \ katta end addition